### ISSUE TITLE
DxfInsert is ignored while conversion to svg

### ISSUE THREAD

**Issue by sampletext32** [ixmilia/converters#2]
All elements inside DxfInserts are completely ignored.
I've managed to overcome this issue with this change
![image](https://user-images.githubusercontent.com/44116740/97178041-002fa880-17a8-11eb-83cc-a27fbcbc4fcf.png)
I don't know if this is the correct way, but I can open a PR for this change, because it's at least working.

**Comment by brettfo** [comment]
`DxfInsert` entities aren't yet supported in the SVG converter.  I'd love to take a PR to implement them, but the proper place to add support for them is in the `ToXElement()` method [here](https://github.com/ixmilia/converters/blob/4aab54424e76d486a5b8c728b499c6400953d1b3/src/IxMilia.Converters/DxfToSvgConverter.cs#L217-L235) and since `ToXElement()` is expected to return a single item, all child entities should be contained in a single `<g></g>` group, possibly something like this:

``` csharp
//...
case DxfInsert insert:
    return insert.ToXElement();
//...

public static XElement ToXElement(this DxfInsert insert)
{
    return new XElement(Xmlns + "g",
        // the sub-entities are contained here
}
```

**Comment by sampletext32** [comment]
@brettfo, there is actually a catch. ```DxfInsert``` needs a whole file to find related ```DxfBlock```. It requires some additional changes.

**Comment by brettfo** [comment]
Good call, I didn't think about that.  If you want to try to solve it then great, if not I'll see if I can find some time to do it.

**Comment by sampletext32** [comment]
I suppose it requires some changes to ```DxfInsert``` in ```Dxf``` repository. I can offer an addition of  ```DxfBlock``` inside ```DxfInsert```, so it can be referenced as is.

**Comment by sampletext32** [comment]
Another way to implement this is to pass ```DxfFile``` inside ```.ToXElement()```, which is faster, but breaks some logic.

**Comment by brettfo** [comment]
I'd rather `DxfFile` get passed through and ignored elsewhere.  E.g.,

``` csharp
public static XElement ToXElement(this DxfEntity entity, DxfFile file)
{
    switch (entity)
    {
        case DxfArc arc:
            return arc.ToXEntity(); // other entities don't need the file, so don't pass it through
        case DxfInsert insert:
            return insert.ToXEntity(file);
        // ...
    }
}
```
